const postDex = [
  {
    id: 3,
    title: "3 Lies Addicts Tell Themselves",
    description: "Sometimes the most damaging lies an addict tells are to themself.",
    category: "addiction",
    to: "/blog/3-lies-addicts-tell-themselves",
    image: 'https://res.cloudinary.com/recovery-ocean/image/upload/v1654553208/man-struggling-with-his-thoughts_xofe0g.jpg',
    alt: "man sitting on chair covering his eyes",
  },
  {
    id: 4,
    title: "The Most Humiliating Moment of My Drug Addiction",
    description: "This is one that I would love to forget.",
    category: "addiction",
    to: "/blog/the-most-humiliating-moment-of-my-drug-addiction",
    image: 'https://res.cloudinary.com/recovery-ocean/image/upload/v1654555339/lava_zqtz2p.jpg',
  },
  {
    id: 5,
    title: "Do Drug Addicts Fall in Love?",
    description: "Not your typically storybook romance. Can addicts actually fall in love?",
    category: "addiction",
    to: "/blog/do-drug-addicts-fall-in-love",
    image: 'https://res.cloudinary.com/recovery-ocean/image/upload/v1654555428/heart_akzboj.jpg',
    attribute: "Photo by Belinda Fewings on Unsplash",
  },
  {
    id: 6,
    title: "Do You Have to Talk at NA Meetings?",
    description: "Find out the rules for participation in an NA meeting.",
    category: "recovery",
    to: "/blog/do-you-have-to-talk-at-na-meetings",
    image: 'https://res.cloudinary.com/recovery-ocean/image/upload/v1654555504/na-meeting_lkczdn.jpg',
    attribute: "By Sincerely Media on Unsplash"
  },
  {
    id: 7,
    title: "Are Drug Addicts Mean?",
    description: "Drugs turn us into completely different people. Are those people always mean?",
    category: "addiction",
    to: "/blog/are-drug-addicts-mean",
    image: 'https://res.cloudinary.com/recovery-ocean/image/upload/v1654555530/aggression_peqzde.jpg',
  },
  {
    id: 8,
    title: "FOMO in Early Recovery",
    description: "Learn how to deal with fear of missing out when you stop using.",
    category: "recovery",
    to: "/blog/fomo-in-early-recovery",
    image: 'https://res.cloudinary.com/recovery-ocean/image/upload/v1654555564/fearful_lucktp.jpg',
  },
  {
    id: 9,
    title: "Why Do Drug Addicts Steal Copper?",
    description: "Stealing copper..? Seems like too much work.",
    category: "addiction",
    to: "/blog/why-do-drug-addicts-steal-copper",
    image: 'https://res.cloudinary.com/recovery-ocean/image/upload/v1654555613/copper-pile_cfl9yz.jpg',
  },
  {
    id: 10,
    title: "Do Drug Addicts Donate Plasma?",
    description: "Is that even allowed?",
    category: "addiction",
    to: "/blog/do-drug-addicts-donate-plasma",
    image: 'https://res.cloudinary.com/recovery-ocean/image/upload/v1654555652/blood-cells_ngi9rb.jpg',
  },
  {
    id: 11,
    title: "How I Managed to Stop Using Heroin",
    description: "Find out how I was able to successfully get off of heroin after eight years of addiction.",
    category: "recovery",
    to: "/blog/how-i-managed-to-stop-using-heroin",
    image: 'https://res.cloudinary.com/recovery-ocean/image/upload/v1654555825/poison_k9xemi.jpg',
  },
  {
    id: 12,
    title: "Encountering Addicts From Our Past",
    description: "How to handle unexpected run-ins with people you used to get high with.",
    category: "recovery",
    to: "/blog/encountering-addicts-from-our-past",
    image: 'https://res.cloudinary.com/recovery-ocean/image/upload/v1654800839/clock_ke5hwm.jpg',
  },
 
]

export default postDex